language: node_js
os: linux
node_js:
    - 8
script: npm run build
deploy:
    local_dir: dist
    script: ls -al
    provider: pages
    cleanup: true
    token: $GITHUB_TOKEN
    keep_history: true
    on:
        branch: master
