language: node_js
os: linux
node_js:
    - 8
script: npm run build
deploy:
    local_dir: dist
    provider: pages
    skip_cleanup: true
    token: $GITHUB_TOKEN
    fqdn: municipales-rennes.fr
    keep_history: true
    on:
        branch: master
