language: node_js
os: linux
node_js:
    - 8
before_script:
    - npm install
script: npm run build
deploy:
    local_dir: dist
    provider: pages
    cleanup: true
    token: $GITHUB_TOKEN
    keep_history: true
    on:
        branch: master
